Changes for PowerAPI monitoring

diff --git a/.github/workflows/build-packages.yml b/.github/workflows/build-packages.yml
--- a/.github/workflows/build-packages.yml
+++ b/.github/workflows/build-packages.yml
@@ -1,267 +1,286 @@
-name: Build Packages
-
-on:
-    push:
-        branches: ['master', 'BRANCH*']
-        paths: ['ganttproject-builder/BUILD-HISTORY-MAJOR']
 env:
-    BUILD_NUMBER: 3300
-    VERSION: 3.3.3300
-    WINDOWS_APP_FOLDER_NAME: GanttProject-3.3
-    MAC_APP_NAME: GanttProject 3.3
-    MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
-    MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
-    MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
-    MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
-
+  BUILD_NUMBER: 3300
+  MACOS_CERTIFICATE: ${{ secrets.PROD_MACOS_CERTIFICATE }}
+  MACOS_CERTIFICATE_NAME: ${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}
+  MACOS_CERTIFICATE_PWD: ${{ secrets.PROD_MACOS_CERTIFICATE_PWD }}
+  MACOS_CI_KEYCHAIN_PWD: ${{ secrets.PROD_MACOS_CI_KEYCHAIN_PWD }}
+  MAC_APP_NAME: GanttProject 3.3
+  VERSION: 3.3.3300
+  WINDOWS_APP_FOLDER_NAME: GanttProject-3.3
 jobs:
-    Linux:
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v3
-            - name: Checkout submodules
-              shell: bash
-              run: |
-                  git submodule sync --recursive
-                  git submodule update --init --force --recursive --depth=1
-                  echo "$VERSION" > ganttproject-builder/VERSION
-            - uses: actions/setup-java@v3
-              with:
-                  distribution: 'liberica'
-                  java-version: 17.0.9
-                  java-package: jdk+fx
-                  cache: 'gradle'
-            - name: Build GanttProject
-              run: |
-                  ./gradlew distbin distzip
-                  ./gradlew -PwithJavafx distdeb
-                  echo "===== PLUGINS ====="
-                  ls ganttproject-builder/dist-bin/plugins/base
-                  echo "===== DISTRIBUTIONS ====="
-                  ls build/distributions
+  Linux:
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v3
+    - continue-on-error: true
+      name: Checkout submodules
+      run: 'git submodule sync --recursive
 
-            - id: 'auth'
-              uses: 'google-github-actions/auth@v1'
-              with:
-                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+        git submodule update --init --force --recursive --depth=1
 
-            - name: 'Set up Cloud SDK'
-              uses: 'google-github-actions/setup-gcloud@v1'
+        echo "$VERSION" > ganttproject-builder/VERSION
 
-            - name: 'Use gcloud CLI'
-              run: 'gcloud info'
+        '
+      shell: bash
+    - continue-on-error: true
+      uses: actions/setup-java@v3
+      with:
+        cache: gradle
+        distribution: liberica
+        java-package: jdk+fx
+        java-version: 17.0.9
+    - continue-on-error: true
+      name: Build GanttProject
+      run: './gradlew distbin distzip
 
-            - name: Upload Packages
-              run: |
-                  #!/bin/sh
-                  cd build/distributions
-                  for f in *; do
-                    gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
-                  done;
+        ./gradlew -PwithJavafx distdeb
 
-    Windows:
-        runs-on: windows-latest
-        steps:
-            - uses: actions/checkout@v3
-            - name: Checkout submodules
-              shell: bash
-              run: |
-                  git submodule sync --recursive
-                  git submodule update --init --force --recursive --depth=1
-                  echo "$VERSION" > ganttproject-builder/VERSION
-            - uses: actions/setup-java@v3
-              with:
-                  distribution: 'liberica'
-                  java-version: 17.0.9
-                  java-package: jdk+fx
-                  cache: 'gradle'
-            - name: Build GanttProject
-              run: |
-                  ./gradlew distbin
-                  echo "===== PLUGINS ====="
-                  ls ganttproject-builder/dist-bin/plugins/base
-            - name: Build MSI installer
-              run: |
-                  build-bin/package-win.bat
+        echo "===== PLUGINS ====="
 
-            - id: 'auth'
-              uses: 'google-github-actions/auth@v1'
-              with:
-                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+        ls ganttproject-builder/dist-bin/plugins/base
 
-            - name: 'Set up Cloud SDK'
-              uses: 'google-github-actions/setup-gcloud@v1'
+        echo "===== DISTRIBUTIONS ====="
 
-            - name: 'Use gcloud CLI'
-              run: 'gcloud info'
+        ls build/distributions
 
-            - name: Upload Packages
-              run: |
-                  gsutil cp build\ganttproject-$env:VERSION.msi gs://dl.ganttproject.biz
-                  gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/ganttproject-$env:VERSION.msi
+        '
+    - continue-on-error: true
+      id: auth
+      uses: google-github-actions/auth@v1
+      with:
+        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+    - continue-on-error: true
+      name: Set up Cloud SDK
+      uses: google-github-actions/setup-gcloud@v1
+    - continue-on-error: true
+      name: Use gcloud CLI
+      run: gcloud info
+    - continue-on-error: true
+      name: Upload Packages
+      run: "#!/bin/sh\ncd build/distributions\nfor f in *; do\n  gsutil cp $f gs://dl.ganttproject.biz\
+        \ && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;\ndone;\n"
+  Windows:
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v3
+    - continue-on-error: true
+      name: Checkout submodules
+      run: 'git submodule sync --recursive
 
-            - name: Install NSIS
-              run: |
-                  iwr -useb get.scoop.sh -outfile 'install.ps1'
-                  .\install.ps1 -RunAsAdmin
-                  scoop update
-                  scoop bucket add extras
-                  scoop install nsis
-            - name: Print NSIS version
-              run: makensis -VERSION
-            - name: Print NSIS compile flags
-              run: makensis -HDRINFO
+        git submodule update --init --force --recursive --depth=1
 
-            - name: Prepare files for NSIS
-              run: |
-                  ./gradlew distwin
-                  echo "===== dist-win ====="
-                  ls ganttproject-builder/dist-win
+        echo "$VERSION" > ganttproject-builder/VERSION
 
-            - name: Build NSIS package
-              run: |
-                  cd ganttproject-builder\dist-win
-                  makensis ganttproject.nsi
-                  dir
-                  mv ganttproject-$env:VERSION.exe ..\..\build
+        '
+      shell: bash
+    - continue-on-error: true
+      uses: actions/setup-java@v3
+      with:
+        cache: gradle
+        distribution: liberica
+        java-package: jdk+fx
+        java-version: 17.0.9
+    - continue-on-error: true
+      name: Build GanttProject
+      run: './gradlew distbin
 
-            - name: Upload Packages
-              run: |
-                  gsutil cp build\ganttproject-$env:VERSION.exe gs://dl.ganttproject.biz
-                  gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/ganttproject-$env:VERSION.exe
+        echo "===== PLUGINS ====="
 
-    macOS_silicon:
-        runs-on: macos-latest-xlarge
-        steps:
-            - uses: actions/checkout@v3
-            - name: Checkout submodules
-              shell: bash
-              run: |
-                  git submodule sync --recursive
-                  git submodule update --init --force --recursive --depth=1
-                  echo "$VERSION" > ganttproject-builder/VERSION
-            - uses: actions/setup-java@v3
-              with:
-                  distribution: 'liberica'
-                  java-version: 17.0.9
-                  java-package: jdk+fx
-                  cache: 'gradle'
-            - name: Build GanttProject
-              run: |
-                  ./gradlew distbin
-                  echo "===== PLUGINS ====="
-                  ls ganttproject-builder/dist-bin/plugins/base
+        ls ganttproject-builder/dist-bin/plugins/base
 
-            - name: Build GanttProject.app
-              run: |
-                  ./build-bin/package-mac.sh
-                  ./build/GanttProject.app/Contents/MacOS/GanttProject -h || echo "failed to run"
+        '
+    - continue-on-error: true
+      name: Build MSI installer
+      run: 'build-bin/package-win.bat
 
-#            - name: Sign GanttProject.app
-#              run: |
-#                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
-#
-#                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-#                  security default-keychain -s build.keychain
-#                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-#                  security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
-#
-#                  build-bin/notarize.sh $VERSION "$MACOS_CERTIFICATE_NAME" "qwer" sign
+        '
+    - continue-on-error: true
+      id: auth
+      uses: google-github-actions/auth@v1
+      with:
+        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+    - continue-on-error: true
+      name: Set up Cloud SDK
+      uses: google-github-actions/setup-gcloud@v1
+    - continue-on-error: true
+      name: Use gcloud CLI
+      run: gcloud info
+    - continue-on-error: true
+      name: Upload Packages
+      run: 'gsutil cp build\ganttproject-$env:VERSION.msi gs://dl.ganttproject.biz
 
-            - name: Create temporary DMG for notarization
-              run: |
-                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject-silicon-$VERSION" --dest build/
-            #            - uses: actions/setup-python@v4
-#              with:
-#                python-version: '3.10'
-#            - name: Build DMG
-#              run: |
-#                  pip install "dmgbuild"
-#                  dmgbuild -s build-cfg/dmgbuild.py "$MAC_APP_NAME" build/ganttproject-$VERSION.dmg
+        gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/ganttproject-$env:VERSION.msi
 
-            - id: 'auth'
-              uses: 'google-github-actions/auth@v1'
-              with:
-                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+        '
+    - continue-on-error: true
+      name: Install NSIS
+      run: 'iwr -useb get.scoop.sh -outfile ''install.ps1''
 
-            - name: 'Set up Cloud SDK'
-              uses: 'google-github-actions/setup-gcloud@v1'
+        .\install.ps1 -RunAsAdmin
 
-            - name: 'Use gcloud CLI'
-              run: 'gcloud info'
+        scoop update
 
-            - name: Upload artifacts
-              run: |
-                  #!/bin/sh
-                  cd build
-                  for f in *.dmg; do
-                    gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
-                  done;
+        scoop bucket add extras
 
-    macOS_intel:
-        runs-on: macos-latest
-        steps:
-            - uses: actions/checkout@v3
-            - name: Checkout submodules
-              shell: bash
-              run: |
-                  git submodule sync --recursive
-                  git submodule update --init --force --recursive --depth=1
-                  echo "$VERSION" > ganttproject-builder/VERSION
-            - uses: actions/setup-java@v3
-              with:
-                  distribution: 'liberica'
-                  java-version: 17.0.9
-                  java-package: jdk+fx
-                  cache: 'gradle'
-            - name: Build GanttProject
-              run: |
-                  ./gradlew distbin
-                  echo "===== PLUGINS ====="
-                  ls ganttproject-builder/dist-bin/plugins/base
+        scoop install nsis
 
-            - name: Build GanttProject.app
-              run: |
-                  ./build-bin/package-mac.sh
-                  ./build/GanttProject.app/Contents/MacOS/GanttProject -h || echo "failed to run"
+        '
+    - continue-on-error: true
+      name: Print NSIS version
+      run: makensis -VERSION
+    - continue-on-error: true
+      name: Print NSIS compile flags
+      run: makensis -HDRINFO
+    - continue-on-error: true
+      name: Prepare files for NSIS
+      run: './gradlew distwin
 
-            #            - name: Sign GanttProject.app
-            #              run: |
-            #                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
-            #
-            #                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-            #                  security default-keychain -s build.keychain
-            #                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
-            #                  security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
-            #
-            #                  build-bin/notarize.sh $VERSION "$MACOS_CERTIFICATE_NAME" "qwer" sign
+        echo "===== dist-win ====="
 
-            - name: Create temporary DMG for notarization
-              run: |
-                  jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject-intel-$VERSION" --dest build/
-            #            - uses: actions/setup-python@v4
-            #              with:
-            #                python-version: '3.10'
-            #            - name: Build DMG
-            #              run: |
-            #                  pip install "dmgbuild"
-            #                  dmgbuild -s build-cfg/dmgbuild.py "$MAC_APP_NAME" build/ganttproject-$VERSION.dmg
+        ls ganttproject-builder/dist-win
 
-            - id: 'auth'
-              uses: 'google-github-actions/auth@v1'
-              with:
-                  credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+        '
+    - continue-on-error: true
+      name: Build NSIS package
+      run: 'cd ganttproject-builder\dist-win
 
-            - name: 'Set up Cloud SDK'
-              uses: 'google-github-actions/setup-gcloud@v1'
+        makensis ganttproject.nsi
 
-            - name: 'Use gcloud CLI'
-              run: 'gcloud info'
+        dir
 
-            - name: Upload artifacts
-              run: |
-                  #!/bin/sh
-                  cd build
-                  for f in *.dmg; do
-                    gsutil cp $f gs://dl.ganttproject.biz && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;
-                  done;
+        mv ganttproject-$env:VERSION.exe ..\..\build
+
+        '
+    - continue-on-error: true
+      name: Upload Packages
+      run: 'gsutil cp build\ganttproject-$env:VERSION.exe gs://dl.ganttproject.biz
+
+        gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/ganttproject-$env:VERSION.exe
+
+        '
+  macOS_intel:
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v3
+    - continue-on-error: true
+      name: Checkout submodules
+      run: 'git submodule sync --recursive
+
+        git submodule update --init --force --recursive --depth=1
+
+        echo "$VERSION" > ganttproject-builder/VERSION
+
+        '
+      shell: bash
+    - continue-on-error: true
+      uses: actions/setup-java@v3
+      with:
+        cache: gradle
+        distribution: liberica
+        java-package: jdk+fx
+        java-version: 17.0.9
+    - continue-on-error: true
+      name: Build GanttProject
+      run: './gradlew distbin
+
+        echo "===== PLUGINS ====="
+
+        ls ganttproject-builder/dist-bin/plugins/base
+
+        '
+    - continue-on-error: true
+      name: Build GanttProject.app
+      run: './build-bin/package-mac.sh
+
+        ./build/GanttProject.app/Contents/MacOS/GanttProject -h || echo "failed to
+        run"
+
+        '
+    - continue-on-error: true
+      name: Create temporary DMG for notarization
+      run: 'jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject-intel-$VERSION"
+        --dest build/
+
+        '
+    - continue-on-error: true
+      id: auth
+      uses: google-github-actions/auth@v1
+      with:
+        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+    - continue-on-error: true
+      name: Set up Cloud SDK
+      uses: google-github-actions/setup-gcloud@v1
+    - continue-on-error: true
+      name: Use gcloud CLI
+      run: gcloud info
+    - continue-on-error: true
+      name: Upload artifacts
+      run: "#!/bin/sh\ncd build\nfor f in *.dmg; do\n  gsutil cp $f gs://dl.ganttproject.biz\
+        \ && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;\ndone;"
+  macOS_silicon:
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v3
+    - continue-on-error: true
+      name: Checkout submodules
+      run: 'git submodule sync --recursive
+
+        git submodule update --init --force --recursive --depth=1
+
+        echo "$VERSION" > ganttproject-builder/VERSION
+
+        '
+      shell: bash
+    - continue-on-error: true
+      uses: actions/setup-java@v3
+      with:
+        cache: gradle
+        distribution: liberica
+        java-package: jdk+fx
+        java-version: 17.0.9
+    - continue-on-error: true
+      name: Build GanttProject
+      run: './gradlew distbin
+
+        echo "===== PLUGINS ====="
+
+        ls ganttproject-builder/dist-bin/plugins/base
+
+        '
+    - continue-on-error: true
+      name: Build GanttProject.app
+      run: './build-bin/package-mac.sh
+
+        ./build/GanttProject.app/Contents/MacOS/GanttProject -h || echo "failed to
+        run"
+
+        '
+    - continue-on-error: true
+      name: Create temporary DMG for notarization
+      run: 'jpackage --type dmg --app-image build/GanttProject.app -n "ganttproject-silicon-$VERSION"
+        --dest build/
+
+        '
+    - continue-on-error: true
+      id: auth
+      uses: google-github-actions/auth@v1
+      with:
+        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+    - continue-on-error: true
+      name: Set up Cloud SDK
+      uses: google-github-actions/setup-gcloud@v1
+    - continue-on-error: true
+      name: Use gcloud CLI
+      run: gcloud info
+    - continue-on-error: true
+      name: Upload artifacts
+      run: "#!/bin/sh\ncd build\nfor f in *.dmg; do\n  gsutil cp $f gs://dl.ganttproject.biz\
+        \ && gsutil acl ch -u AllUsers:R gs://dl.ganttproject.biz/$f;\ndone;\n"
+name: Build Packages
+on:
+  repository_dispatch:
+    types: trigger-ga___build-packages.yml
